server:
  port: 18085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848
    sentinel:
      transport:
        dashboard: 192.168.0.101:8858
        port: 8719
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
  zipkin:
    base-url: http://192.168.0.101:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_sms?useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  redis:
    host: 192.168.0.101
    port: 6379
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  type-aliases-package: com.atguigu.gmall.sms.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis-plus配置控制台打印完整带参数sql语句
seata:
  enabled: true
