#SpringCloud相关配置
server:
  #端口号
  port: 18090
spring:
  cloud:
    #nacos配置
    nacos:
      discovery:
        #注册中心地址
        server-addr: 192.168.0.101:8848
    #sentinel配置
    sentinel:
      transport:
        dashboard: 192.168.0.101:8080
        # 服务与sentinel交互使用的端口号，一个服务可以有多个端口号
        port: 8719
  #zipkin配置
  zipkin:
    base-url: http://192.168.0.101:9411
    discovery-client-enabled: false
    #发送方式web(http)
    sender:
      type: web
  #sleuth相关配置
  sleuth:
    #链路追踪的采集率
    sampler:
      probability: 1
  #thymeleaf相关配置
  thymeleaf:
    cache: false
  #mysql数据源相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart?useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  #redis相关配置
  redis:
    host: 192.168.0.101
    password: 123456
  #RabbitMq相关配置
  rabbitmq:
    host: 192.168.0.101
    port: 5672
    virtual-host: /hxy
    username: hxy
    password: hxy20010302
    # 消费者
    listener:
      simple:
        # 消费者确认模式 none：不确认模式(只要消息到消费者即被确认) auto：自动确认模式(只要消费者没有异常就会被确认，有异常则会无限重试) manual：手动确认模式
        acknowledge-mode: manual
        # 能者多劳
        prefetch: 1
        # 多线程消费
        concurrency: 4
#开启feign的sentinel功能
feign:
  sentinel:
    enabled: true
#线程池相关配置
threadPool:
  #核心线程数
  corePoolSize: 100
  #最大线程数
  maximumPoolSize: 200
  #线程空闲时存活时间
  keepAliveTime: 60
  #阻塞队列大小
  blockingQueueSize: 500

