server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        #同步请求过滤器
        - id: index-route
          uri: lb://index-service
          predicates:
            - Host=gmall.com,www.gmall.com
          filters:
            - AddResponseHeader=xxx, yyy
            - Test
        #专门为异步请求提供
        - id: index-route2
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com