#SpringCloud相关配置
server:
  #端口号
  port: 18081
spring:
  cloud:
    #nacos配置
    nacos:
      discovery:
        #注册中心地址
        server-addr: 192.168.0.101:8848
    # sentinel配置
    sentinel:
      transport:
        dashboard: 192.168.0.101:8080
        # 服务与sentinel交互使用的端口号，一个服务可以有多个端口号
        port: 8719
    #seata配置
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
  #zipkin相关配置
  zipkin:
    base-url: http://192.168.0.101:9411
    discovery-client-enabled: false
    #发送方式web(http)
    sender:
      type: web
  #链路追踪的采集率
  sleuth:
    sampler:
      probability: 1
  #SpringBoot的数据源和redis相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_pms?useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  #RabbitMq相关配置
  rabbitmq:
    host: 192.168.0.101
    port: 5672
    virtual-host: /hxy
    username: hxy
    password: hxy20010302
    #生产者确认类型：none-不确认，simple-阻塞方式确认，correlated-异步监听方式确认
    publisher-confirm-type: correlated
    #生产者确定消息是否到达队列
    publisher-returns: true
  #redis相关配置
  redis:
    host: localhost
    port: 6379

#开启feign的sentinel功能
feign:
  sentinel:
    enabled: true
  # 设置 feign 超时时间
  client:
    config:
      # default 设置的全局超时时间，指定服务名称可以设置单个服务的超时时间
      default:
        connectTimeout: 5000
        readTimeout: 5000

#Mybatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/pms/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entitys
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis-plus配置控制台打印完整带参数sql语句
seata:
  enabled: true

