server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848
    # sentinel配置
    sentinel:
      transport:
        dashboard: 192.168.0.101:8858
        # pms与sentinel交互端口号，统一设置默认值8719，如被占用自动递增
        port: 8719
  # zipkin配置
  zipkin:
    base-url: http://192.168.0.101:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_wms?useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  redis:
    host: 192.168.0.101
    port: 6379
# feign配置
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/wms/xx/*.xml
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis-plus配置控制台打印完整带参数sql语句

# 修改日志输出级别，输出mp的sql语句
logging:
  level:
    com.atguigu.gmall.wms: debug